# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote', to='finder_app.User')),
                ('written_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote_to', to='finder_app.User')),
            ],
        ),
    ]
